pipeline:
  poc:
    image: vigohe/drone-var-poc:b-13
    vault:
      - docker_username=secret/docker-poc#username
      - docker_password=secret/docker-poc#password
    secrets: [ username, password ]