pipeline:
  poc:
    image: vigohe/drone-var-poc:b-6
    vault:
      - docker_username=secret/docker-poc#username
      - docker_password=secret/docker-poc#password
      - username=$USERNAME
      - password=$PASSWORD
    secrets: [ username, password ]