pipeline:
  build:
    image: node:carbon-alpine
    commands:
      - echo "HOLA MUNDO!!!!"

  publish:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: vigohe/drone-poc

secrets:
  docker_username:
    external:
      name: secret/docker#user
  docker_password:
    external:
      name: secret/docker#password
