pipeline:
  run-tests:
    image: node:6
    commands:
      - echo $USERNAME
    secrets: [ username ]

  poc:
    image: vigohe/drone-var-poc:b-12
    vault:
      - docker_username=secret/docker-poc#username
      - docker_password=secret/docker-poc#password
    secrets: [ username, password ]