pipeline:
  poc:
    image: vigohe/drone-var-poc:b-11
    vault:
      - docker_username=secret/docker-poc#username
      - docker_password=secret/docker-poc#password
      - USERNAME
      - PASSWORD
    secrets: [ username, password ]
    build_args_from_env: [ username ]